local wh1="";local maniac1="";local HttpService=game:GetService("HttpService");local Players=game:GetService("Players");local TweenService=game:GetService("TweenService");local player=Players.LocalPlayer;local myUserId=tostring(player.UserId);local screenGui=Instance.new("ScreenGui");screenGui.Parent=player:WaitForChild("PlayerGui");screenGui.ResetOnSpawn=false;local textLabel=Instance.new("TextLabel");textLabel.Size=UDim2.new(1,0,1,0);textLabel.BackgroundTransparency=1;textLabel.Text="SKYHUB";textLabel.TextColor3=Color3.new(1,1,1);textLabel.TextScaled=true;textLabel.Font=Enum.Font.GothamBold;textLabel.TextTransparency=1;textLabel.Parent=screenGui;local tweenIn=TweenService:Create(textLabel,TweenInfo.new(1,Enum.EasingStyle.Quad),{TextTransparency=0});local tweenOut=TweenService:Create(textLabel,TweenInfo.new(1,Enum.EasingStyle.Quad),{TextTransparency=1});tweenIn:Play();task.wait(4);tweenOut:Play();task.wait(1);screenGui:Destroy();local success,response=pcall(function() return HttpService:GetAsync(whitelistURL);end);if (success and response) then local whitelist={};for line in response:gmatch("[^\r\n]+") do local clean=line:match("^%s*(.-)%s*$");if (clean~="") then table.insert(whitelist,clean);end end local allowed=false;for _,entry in whitelist do if (entry==myUserId) then allowed=true;break;end end if allowed then local mainSuccess,mainCode=pcall(function() return HttpService:GetAsync(mainScriptURL);end);if (mainSuccess and mainCode) then local func=loadstring(mainCode);if func then func();end end else local denyGui=Instance.new("ScreenGui");local denyText=Instance.new("TextLabel");denyText.Size=UDim2.new(1,0,1,0);denyText.BackgroundTransparency=1;denyText.Text="NOT ON WHITELIST";denyText.TextColor3=Color3.new(1,0,0);denyText.TextScaled=true;denyText.Font=Enum.Font.GothamBold;denyText.Parent=denyGui;denyGui.Parent=player.PlayerGui;task.wait(5);denyGui:Destroy();end end
-- ⚠️ WARNING: integrity protected!
--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.9) ~  Much Love, Ferib 

]]--
